# Generated by Django 5.2.6 on 2025-09-26 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_products_pr_created_bce1a7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stockreservation",
            name="products_st_expires_6835f4_idx",
        ),
        migrations.RenameIndex(
            model_name="productstock",
            new_name="stock_product_idx",
            old_name="products_pr_product_cb8c7f_idx",
        ),
        migrations.RenameIndex(
            model_name="productstock",
            new_name="stock_available_idx",
            old_name="products_pr_availab_e6333c_idx",
        ),
        migrations.RenameIndex(
            model_name="productstock",
            new_name="stock_warehouse_idx",
            old_name="products_pr_warehou_021dd2_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="reservation_stock_status_idx",
            old_name="products_st_product_dc6c81_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="reservation_user_status_idx",
            old_name="products_st_user_id_d98b38_idx",
        ),
        migrations.RenameIndex(
            model_name="stockreservation",
            new_name="reservation_order_idx",
            old_name="products_st_order_i_11ffe3_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransaction",
            new_name="transaction_stock_created_idx",
            old_name="products_st_product_8e4d21_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransaction",
            new_name="transaction_type_created_idx",
            old_name="products_st_transac_6c0ce1_idx",
        ),
        migrations.RenameIndex(
            model_name="stocktransaction",
            new_name="transaction_reference_idx",
            old_name="products_st_referen_d98c37_idx",
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                condition=models.Q(("available_stock__gt", 0)),
                fields=["product", "available_stock"],
                name="stock_product_available_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["product", "updated_at"], name="stock_product_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                condition=models.Q(
                    ("available_stock__lte", models.F("min_stock_level"))
                ),
                fields=["available_stock", "min_stock_level"],
                name="stock_low_stock_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(fields=["-updated_at"], name="stock_updated_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["expires_at", "status"],
                name="reservation_expire_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["product_stock", "status", "expires_at"],
                name="rsv_stock_status_expire_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["user_id", "-created_at"], name="reservation_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["-created_at"], name="reservation_created_desc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["confirmed_at"], name="reservation_confirmed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["cancelled_at"], name="reservation_cancelled_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["product_stock", "transaction_type", "-created_at"],
                name="txn_stock_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["-created_at"], name="transaction_created_desc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["reference_type", "reference_id", "-created_at"],
                name="transaction_ref_created_idx",
            ),
        ),
    ]
